set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property PACKAGE_PIN B3 [get_ports {out[3]}]
set_property PACKAGE_PIN A3 [get_ports {out[2]}]
set_property PACKAGE_PIN B4 [get_ports {out[1]}]
set_property PACKAGE_PIN A4 [get_ports {out[0]}]
set_property PACKAGE_PIN F14 [get_ports clk]
set_property PACKAGE_PIN J1 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]

set_property IOSTANDARD LVCMOS33 [get_ports {count[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[0]}]
set_property PACKAGE_PIN B3 [get_ports {count[3]}]
set_property PACKAGE_PIN A3 [get_ports {count[2]}]
set_property PACKAGE_PIN B4 [get_ports {count[1]}]
set_property PACKAGE_PIN A4 [get_ports {count[0]}]

