set_property PACKAGE_PIN K1 [get_ports a]
set_property PACKAGE_PIN K2 [get_ports b]
set_property PACKAGE_PIN A4 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property DRIVE 12 [get_ports c]
